# Copy to infra/env.production on the LAN host, then run via:
#   op run --env-file infra/env.production -- docker compose -f infra/docker-compose.prod.yml config
#   op run --env-file infra/env.production -- docker compose -f infra/docker-compose.prod.yml up -d --build
#
# Keep only op:// references or placeholders here. Do not commit materialized secrets.

TZ=Asia/Tokyo
APP_ENV=production
JSON_LOGS=true
LOG_LEVEL=INFO
MARKET_DATA_STALE_WARN_SECONDS=180

# Managed GCP Pub/Sub. Do not set PUBSUB_EMULATOR_HOST in production.
PUBSUB_PROJECT_ID=op://roboinvest/production/PUBSUB_PROJECT_ID
GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp-pubsub-sa.json
GOOGLE_APPLICATION_CREDENTIALS_HOST_PATH=/dev/shm/roboinvest/gcp-pubsub-sa.json
# Materialize op://roboinvest/production/GOOGLE_APPLICATION_CREDENTIALS_JSON to /dev/shm/roboinvest/gcp-pubsub-sa.json before compose up.

# Cloud Logging collector. Enable with docker compose --profile observability.
OTEL_COLLECTOR_IMAGE=otel/opentelemetry-collector-contrib:0.153.0

# Supabase Cloud
SUPABASE_URL=op://roboinvest/production/SUPABASE_URL
SUPABASE_SECRET_KEY=op://roboinvest/production/SUPABASE_SECRET_KEY

# Universe Scanner batch. J-Quants API v2 uses API key auth.
JQUANTS_API_KEY=op://roboinvest/jquants/JQUANTS_API_KEY
# Optional only for legacy v1 auth flow:
# JQUANTS_REFRESH_TOKEN=op://roboinvest/jquants/JQUANTS_REFRESH_TOKEN
JQUANTS_PLAN=standard
JQUANTS_API_VERSION=v2
JQUANTS_API_BASE=https://api.jquants.com/v2
SCAN_STATIC_MIN_TURNOVER_JPY=200000000
SCAN_STATIC_PRICE_MIN=300
SCAN_STATIC_PRICE_MAX=5000
SCAN_STATIC_MIN_LOT_SIZE=100
SCAN_STATIC_MAX_MIN_LOT_NOTIONAL_JPY=500000
SCAN_WEIGHT_RISK_PENALTY=1.0
SCAN_RISK_VOLATILITY_Z_WEIGHT=0.75
SCAN_RISK_NEGATIVE_MOMENTUM_Z_WEIGHT=1.0
SCAN_RISK_VOLUME_SURGE_Z_WEIGHT=0.5
SCAN_RISK_OVERHEAT_MOMENTUM_Z_WEIGHT=0.5
SCAN_RISK_VOLUME_SURGE_Z=1.5
SCAN_RISK_OVERHEAT_MOMENTUM_Z=1.5

# kabu Station via LAN Caddy reverse proxy
KABU_API_BASE_URL=http://<windows-host-ip>:28080/kabusapi
KABU_WS_URL=ws://<windows-host-ip>:28080/kabusapi/websocket
KABU_API_PASSWORD=op://roboinvest/kabu/KABU_API_PASSWORD
KABU_ORDER_PASSWORD=op://roboinvest/kabu/KABU_ORDER_PASSWORD
FEEDER_KABU_DEFAULT_EXCHANGE=1
KABU_DEFAULT_EXCHANGE=9
KABU_ACCOUNT_TYPE=4

# Start production deployments in paper mode.
TRADE_MODE=paper

# OMS Live safety knobs. Keep dry-run true until the live readiness gate passes.
OMS_LIVE_DRY_RUN=true
OMS_LIVE_STOP_MONITOR_ENABLED=false
OMS_LIVE_PUBSUB_SUBSCRIPTION_RAW_MARKET_DATA=oms-live-raw-books
OMS_LIVE_MAX_QTY_PER_ORDER=100
LIVE_SIGNAL_MAX_AGE_SECONDS=300
LIVE_DAY_NEW_BUY_START_TIME=09:15
LIVE_DAY_NEW_BUY_CUTOFF_TIME=14:30
MAX_HOLD_MINUTES=45
CLOSEOUT_ORDER_FILL_TIMEOUT_SECONDS=2400
OMS_LIVE_ALLOWED_SYMBOLS=7203
PAPER_DAY_STOP_MONITOR_ENABLED=true

# Strategy parameters known from the verified local setup.
STRATEGIES_ENABLED=rsi_threshold,bollinger_breakout
AI_TRIGGER_MIN_CONFIDENCE=0.8
PUBSUB_TOPIC_AI_TRIGGERS=strategy-ai-triggers
SMA_MIN_GAP_RATIO=0.005
RSI_BUY_THRESHOLD=25.0
RSI_SELL_THRESHOLD=75.0
BOLLINGER_BREAKOUT_TOLERANCE=0.15
ENTRY_VOLUME_RATIO_MIN=
ENTRY_MAX_SPREAD_BPS=30
ENTRY_MAX_SPREAD_TICKS=1
ENTRY_MIN_ASK_DEPTH_5=1000
ENTRY_MIN_BOOK_IMBALANCE_5=0.0
ENTRY_MIN_MINUTES_FROM_OPEN=15
ENTRY_MIN_MINUTES_TO_CLOSE=60
ENTRY_MAX_BOOK_AGE_SECONDS=30
ENTRY_MAX_PRICE=5000
RSI_BUY_REQUIRE_PRICE_ABOVE_VWAP=false
RSI_BUY_REQUIRE_SMA_UPTREND=false
BOLLINGER_BUY_REQUIRE_LOWER_RECLAIM=false
BOLLINGER_BUY_REQUIRE_PRICE_ABOVE_VWAP=false
BOLLINGER_BUY_REQUIRE_SMA_UPTREND=false

# Aggregator thresholds. Keep consensus permissive while filtering weak single-source signals.
MIN_CONFIDENCE_RULE_ONLY=0.45
MIN_CONFIDENCE_AI_ONLY=0.5
MIN_CONFIDENCE_CONSENSUS=0.3
SELL_REQUIRES_POSITION=true

# AI strategy
LLM_PROVIDER=gemini
GEMINI_API_KEY=op://roboinvest/ai/GEMINI_API_KEY
GEMINI_MODEL=gemini-2.5-flash
AI_MIN_INTERVAL_SECONDS=300
AI_MAX_OUTPUT_TOKENS=2048
AI_PUBSUB_PULL_MAX_MESSAGES=5
OMS_PAPER_PUBSUB_PULL_MAX_MESSAGES=500
OMS_PAPER_RAW_BOOK_DRAIN_MAX_BATCHES=10
PUBSUB_SUBSCRIPTION_AI_FEATURES=strategy-ai-rule-signals

# Feature storage
STORAGE_TICK_RESOLUTION=1s
ORDER_BOOK_MAX_AGE_SECONDS=10

# Risk defaults
CAPITAL=1000000
MAX_RISK_PER_TRADE_PCT=0.02
SWING_RISK_SCALE=0.5
DEFAULT_STOP_LOSS_SPREAD_PCT=0.02
PAPER_BUY_LIMIT_OFFSET_TICKS=3
PAPER_SYMBOL_ORDER_COOLDOWN_SECONDS=300
MIN_LOT_SIZE=100

# Gateway safety gates for paper observation.
MARKET_REGIME_GATEWAY_LOG_ONLY_ENABLED=true
MARKET_REGIME_GATEWAY_GUARD_ENABLED=false
MARKET_REGIME_PAPER_GUARD_ENABLED=true
SOFT_LOSS_THROTTLE_LOG_ONLY_ENABLED=true
SOFT_LOSS_THROTTLE_GUARD_ENABLED=true
SOFT_LOSS_LIMIT_JPY=20000
EXECUTION_GATE_LOG_ONLY_ENABLED=true
EXECUTION_GATE_GUARD_ENABLED=true
EXECUTION_GATE_MAX_SPREAD_BPS=30
EXECUTION_GATE_MAX_SPREAD_TICKS=2
EXECUTION_GATE_MIN_ASK_DEPTH_MULTIPLIER=3
